#! /bin/sh

# Fix for Arduino IDE tiling
export _JAVA_AWT_WM_NONREPARENTING=1

# Dark mode for calibre
export CALIBRE_USE_DARK_PALETTE=1

# -x eXact
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x dunst > /dev/null || dunst &

# Set screensaver time (seconds) - this activates xss-lock
xset s 180
export XSECURELOCK_DISCARD_FIRST_KEYPRESS=0
pgrep -x xss-lock > /dev/null || xss-lock xsecurelock &

feh --bg-center --randomize ~/.wallpaper/* &

# Touchpad fixes
xinput set-prop 11 311 1 # Natural scrolling
xinput set-prop 11 312 1

xinput set-prop 11 331 1 # Touch to click
xinput set-prop 11 332 1

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

$HOME/.config/polybar/launch.sh
