#! /bin/sh

# -x eXact
pgrep -x picom > /dev/null || picom --experimental-backends &
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x dunst > /dev/null || dunst &
pgrep -x xss-lock > /dev/null || xss-lock xsecurelock &

# Polkit agent - so that we can mount drives from the file manager
# -f full process name - otherwise pgrep only looks at the first 15 chars
pgrep -f lxqt-policykit-agent > /dev/null || lxqt-policykit-agent &

# Set screensaver time (seconds) - this activates xss-lock
xset s 180

# Wallpaper
feh --bg-fill --randomize ~/.config/wallpapers/* &

# Set default cursor
xsetroot -cursor_name left_ptr

# Touchpad fixes
xinput set-prop 11 311 1 # Natural scrolling
xinput set-prop 11 312 1

xinput set-prop 11 331 1 # Touch to click
xinput set-prop 11 332 1

# So that fonts look good on Java/Wine applications
xsettingsd &

# Alt-tab script
python3 ~/.config/bspwm/AltTabber.py &

bspc monitor -d I II III IV V VI VII VIII IX 

bspc config border_width          2
bspc config window_gap            10

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

bspc rule -a scratchterm sticky=on state=floating locked=on rectangle=1916x465+0+25
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

$HOME/.config/polybar/launch.sh
